# Generated by Django 2.0.6 on 2018-06-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_report',
            field=models.DateTimeField(blank=True, verbose_name='date submitted'),
        ),
    ]
