# Generated by Django 2.0.6 on 2018-06-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180622_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_report',
            field=models.DateTimeField(default=None, verbose_name='date submitted'),
        ),
    ]
