# Generated by Django 2.0.6 on 2018-06-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180622_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_report',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date submitted'),
        ),
    ]
