# Generated by Django 2.0.6 on 2018-06-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_profile_last_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_poll',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='models_date submitted'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_report',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='report_date submitted'),
        ),
    ]
