# Generated by Django 2.0.6 on 2018-06-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180622_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='report_tmp',
            field=models.IntegerField(default=0),
        ),
    ]
